openapi: 3.0.0
info:
  title: Epub Web Library
  description: Managing epub libraries on the web
  version: 1.0.0
tags:
  - name: User
    description: User operations
  - name: Library
    description: Library operations
paths:
  /api/users:
    post:
      tags:
        - User
      summary: Register a new user
      requestBody:
        $ref: '#/components/requestBodies/userCredentials'
      responses:
        '200':
          $ref: '#/components/responses/token'
        '400':
          $ref: '#/components/responses/badRequest'
  /api/users/login:
    post:
      tags:
        - User
      summary: Log user in
      requestBody:
        $ref: '#/components/requestBodies/userCredentials'
      responses:
        '200':
          $ref: '#/components/responses/token'
        '400':
          $ref: '#/components/responses/badRequest'
  /api/users/passwordchange:
    post:
      tags:
        - User
      summary: Change password for user
      security:
        - JWT: []
      requestBody:
        $ref: '#/components/requestBodies/passwordChange'
      responses:
        '200':
          $ref: '#/components/responses/success'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
  /api/epubs:
    post:
      tags:
        - Library
      summary: Upload a new epub
      security:
        - JWT: []
      requestBody:
        $ref: '#/components/requestBodies/epubFile'
      responses:
        '200':
          $ref: '#/components/responses/epubMetadata'
        '401':
          $ref: '#/components/responses/unauthorized'
        '415':
          $ref: '#/components/responses/unsupportedMediaType'
components:
  schemas:
    epubMetadata:
      type: object
      properties:
        epubId:
          type: integer
        owner:
          type: string
          nullable: true
        contributors:
          type: string
          nullable: true
        coverage:
          type: string
          nullable: true
        creators:
          type: string
          nullable: true
        date:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        format:
          type: string
          nullable: true
        identifier:
          type: string
          nullable: true
        languages:
          type: string
          nullable: true
        publisher:
          type: string
          nullable: true
        relation:
          type: string
          nullable: true
        rights:
          type: string
          nullable: true
        source:
          type: string
          nullable: true
        subject:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      required:
        - epubId
        - owner
        - contributors
        - coverage
        - creators
        - date
        - description
        - format
        - identifier
        - languages
        - publisher
        - relation
        - rights
        - source
        - subject
        - title
        - type
    passwordChange:
      type: object
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
      required:
        - currentPassword
        - newPassword
    token:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    userCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
  requestBodies:
    epubFile:
      required: true
      description: Epub file to upload
      content:
        application/epub+zip: {}
    passwordChange:
      required: true
      description: Password change request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/passwordChange'
          examples:
            passwordChange:
              summary: A password change
              value:
                currentPassword: password
                newPassword: 1Pa$sword
    userCredentials:
      required: true
      description: User credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/userCredentials'
          examples:
            userCredentials:
              summary: A user
              value:
                username: user
                password: secretpassword
  responses:
    badRequest:
      description: Bad Request
    epubMetadata:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/epubMetadata'
          examples:
            nulls:
              summary: Properties are null
              value:
                epubId: 1
                owner: user
                contributors: null
                coverage: null
                creators: null
                date: null
                description: null
                format: null
                identifier: null
                languages: null
                publisher: null
                relation: null
                rights: null
                source: null
                subject: null
                title: null
                type: null
    success:
      description: Success
    token:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/token'
          examples:
            jwt:
              summary: A JSON web token
              value:
                token: Header.Payload.Signature
    unauthorized:
      description: Unauthorized
    unsupportedMediaType:
      description: Unsupported Media Type
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
