openapi: 3.0.0
info:
  title: EPUB Web Library
  description: Managing EPUB libraries on the web
  version: 1.0.0
tags:
  - name: User
    description: User operations
  - name: Library
    description: Library operations
paths:
  /api/users:
    post:
      tags:
        - User
      summary: Register a new user
      requestBody:
        $ref: '#/components/requestBodies/userCredentials'
      responses:
        '200':
          $ref: '#/components/responses/token'
        '400':
          $ref: '#/components/responses/badRequest'
  /api/users/{username}:
    delete:
      tags:
        - User
      summary: Delete user
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        '204':
          $ref: '#/components/responses/success'
        '401':
          $ref: '#/components/responses/unauthorized'
  /api/users/login:
    post:
      tags:
        - User
      summary: Log user in
      requestBody:
        $ref: '#/components/requestBodies/userCredentials'
      responses:
        '200':
          $ref: '#/components/responses/token'
        '400':
          $ref: '#/components/responses/badRequest'
  /api/users/passwordchange:
    post:
      tags:
        - User
      summary: Change password for user
      security:
        - JWT: []
      requestBody:
        $ref: '#/components/requestBodies/passwordChange'
      responses:
        '204':
          $ref: '#/components/responses/success'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
  /api/epubs:
    post:
      tags:
        - Library
      summary: Upload a new EPUB
      security:
        - JWT: []
      requestBody:
        $ref: '#/components/requestBodies/epubFile'
      responses:
        '200':
          $ref: '#/components/responses/epubMetadata'
        '401':
          $ref: '#/components/responses/unauthorized'
        '415':
          $ref: '#/components/responses/unsupportedMediaType'
components:
  schemas:
    epubMetadata:
      type: object
      description: EPUB metadata
      properties:
        epubId:
          description: Id of the EPUB
          type: integer
        owner:
          description: Owner of the EPUB
          type: string
          nullable: true
        tags:
          description: Tags of the EPUB
          type: array
          items:
            type: string
        contributors:
          description: The contributor property is used to represent the name of a person, organization, etc. that played a secondary role in the creation of the content of an EPUB Publication.
          type: string
          nullable: true
        coverage:
          description: The spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
          type: string
          nullable: true
        creators:
          description: The creators property represents the names of people, organizations, etc. responsible for the creation of the content of the Rendition.
          type: string
          nullable: true
        date:
          description: The date property MUST only be used to define the publication date of the EPUB Publication. The publication date is not the same as the last modified date (the last time the Rendition was changed).
          type: string
          nullable: true
        description:
          description: An account of the resource.
          type: string
          nullable: true
        format:
          description: The file format, physical medium, or dimensions of the resource.
          type: string
          nullable: true
        identifier:
          description: The identifier property contains an identifier associated with the given Rendition, such as a UUID, DOI or ISBN.
          type: string
          nullable: true
        languages:
          description: The languages property specifies the languages of the content of the given Rendition.
          type: string
          nullable: true
        publisher:
          description: An entity responsible for making the resource available.
          type: string
          nullable: true
        relation:
          description: A related resource.
          type: string
          nullable: true
        rights:
          description: Information about rights held in and over the resource.
          type: string
          nullable: true
        source:
          description: A related resource from which the described resource is derived.
          type: string
          nullable: true
        subject:
          description: The subject property identifies the subject of the EPUB Publication.
          type: string
          nullable: true
        title:
          description: The title property represents the name given to the EPUB Publication.
          type: string
          nullable: true
        type:
          description: The type property is used to indicate that the given EPUB Publication is of a specialized type (e.g., annotations or a dictionary packaged in EPUB format).
          type: string
          nullable: true
      required:
        - epubId
        - owner
        - tags
        - contributors
        - coverage
        - creators
        - date
        - description
        - format
        - identifier
        - languages
        - publisher
        - relation
        - rights
        - source
        - subject
        - title
        - type
    passwordChange:
      type: object
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
      required:
        - currentPassword
        - newPassword
    token:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    userCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
  parameters:
    username:
      required: true
      in: path
      name: username
      schema:
        type: string
      description: The username
  requestBodies:
    epubFile:
      required: true
      description: EPUB file to upload
      content:
        application/epub+zip: {}
    passwordChange:
      required: true
      description: Password change request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/passwordChange'
          examples:
            passwordChange:
              summary: A password change
              value:
                currentPassword: password
                newPassword: 1Pa$sword
    userCredentials:
      required: true
      description: User credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/userCredentials'
          examples:
            userCredentials:
              summary: A user
              value:
                username: user
                password: secretpassword
  responses:
    badRequest:
      description: Bad Request
    epubMetadata:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/epubMetadata'
          examples:
            nulls:
              summary: Properties are null
              value:
                epubId: 1
                owner: user
                tags: []
                contributors: null
                coverage: null
                creators: null
                date: null
                description: null
                format: null
                identifier: null
                languages: null
                publisher: null
                relation: null
                rights: null
                source: null
                subject: null
                title: null
                type: null
    success:
      description: Success
    token:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/token'
          examples:
            jwt:
              summary: A JSON web token
              value:
                token: Header.Payload.Signature
    unauthorized:
      description: Unauthorized
    unsupportedMediaType:
      description: Unsupported Media Type
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
